Update ModeMap.py
When Qrange2 is not None , an error occurs because it becomes an array. 
---
Traceback (most recent call last):
  File "/home/sr2/sungh20.kim/.local/bin/ModeMap.py", line 179, in <module>
    if args.MapMode == '2D' and args.QRange2 == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
---